---
excludes:
  paths:
    - pattern: "deps/**"
      reason: "TEST_OF"
      comment:
        "Licenses contained in this directory are used for testing and do not\
        \ apply to the OSS Review Toolkit."
    - pattern: "requirements*txt"
      reason: "DEV_DEPENDENCY_OF"
      comment:
        "Dev components"
  scopes:
    - pattern: "(test.*|funTest.*)"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only. Not part of released artifacts."
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for development only. Not part of released artifacts"
